### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [brohrer/publications#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by brohrer** [comment]
Thanks for the reminder karan. In principle I agree with you. I try to include a license (MIT is my go-to) in all my software projects. In this particular where I am listing my publications, the licensing is a little more complex. In some cases, I'm posting material for which I don't have the copyright. And none of it is code. With respect for the suggestion, I'm going to decline.

**Comment by karan** [comment]
Hey no worries! Thanks for being considerate though.
